# Generated by Django 5.1.4 on 2024-12-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_city_store_is_main_store_state_store_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='vendor',
        ),
    ]
