# Generated by Django 5.1.4 on 2024-12-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_options_alter_openingperiod_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='city_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ar',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='store',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='store',
            name='state_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='state_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
