# Generated by Django 5.1.4 on 2025-01-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_remove_store_is_pickup_store_store_is_drive_thru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreStock',
        ),
    ]
