# Generated by Django 5.1.4 on 2025-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_delete_storestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='state_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='state_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
