# Generated by Django 5.1.4 on 2025-01-29 10:12

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_remove_storeaddress_city_alter_storeaddress_line4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(46.6753, 24.7136), srid=4326, verbose_name='Location'),
        ),
    ]
