# Generated by Django 5.1.4 on 2025-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_storeaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.FloatField(default=0, help_text='Average rating of the store', verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='store',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings received', verbose_name='Total Ratings'),
        ),
    ]
