# Generated by Django 5.1.4 on 2025-02-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_store'),
        ('stores', '0017_store_rating_store_total_ratings'),
        ('user', '0016_merge_20250212_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate from 1 to 5 stars', verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback about your experience', null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_ratings', to='user.customer', verbose_name='Customer')),
                ('order', models.OneToOneField(help_text='The order associated with this rating', on_delete=django.db.models.deletion.CASCADE, related_name='store_rating', to='order.order', verbose_name='Order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='stores.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Store Rating',
                'verbose_name_plural': 'Store Ratings',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['store', 'rating'], name='stores_stor_store_i_7282a2_idx'), models.Index(fields=['customer', 'created_at'], name='stores_stor_custome_17e621_idx')],
                'unique_together': {('store', 'order')},
            },
        ),
    ]
