# Generated by Django 5.1.4 on 2025-03-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_storerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Minimum order value required for this store', max_digits=12, verbose_name='Minimum Order Value'),
        ),
        migrations.AlterField(
            model_name='store',
            name='total_ratings',
            field=models.PositiveIntegerField(default=15, help_text='Total number of ratings received', verbose_name='Total Ratings'),
        ),
    ]
