# Generated by Django 5.1.4 on 2025-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_store_minimum_order_value_alter_store_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings received', verbose_name='Total Ratings'),
        ),
    ]
